DarkSea Implementation Bitvector Abstraction
ultimate-pa/ultimate pull request #581
Opened 2022-02-01 13:40 UTC by cyruliu

Hi @danieldietsch,

I tried to squash the commits on my local, and the PR lost git diff tracks on github (maybe I used the wrong method), it was forced to close after I pushed to its remote, so I recovered it back and create this second one, sorry about the noise. I didn't know there will be a `squash and merge` option for PR here on Github, it should appear after we resolve the conflicts in the end, should we try to resolve the conflict files first?

Best,
Cyrus

2022-02-01 15:32 UTC, danieldietsch requested changes
Lets wait for the results of the nightly build, then we should be able to merge.

2022-02-01 15:32 UTC, danieldietsch commented on trunk/source/CACSL2BoogieTranslator/src/de/uni_freiburg/informatik/ultimate/cdt/translation/implementation/FlatSymbolTable.java
> +
Can you remove additional whitespace?

2022-02-01 15:32 UTC, danieldietsch commented on trunk/source/CACSL2BoogieTranslator/src/de/uni_freiburg/informatik/ultimate/cdt/translation/implementation/FlatSymbolTable.java
> + * @return global scope.
Please do not use your name in a method, it just confuses people that do not know you. Also, you should not expose a writable variant of the global scope. Wrap it in Collections.unmodifiableMap()

2022-02-01 15:32 UTC, danieldietsch commented on trunk/source/CACSL2BoogieTranslator/src/de/uni_freiburg/informatik/ultimate/cdt/translation/implementation/base/CHandler.java
> +		//@CL, with binary expression, we check bitwise operator first
What does @CL mean?

2022-02-01 15:32 UTC, danieldietsch commented on trunk/source/CACSL2BoogieTranslator/src/de/uni_freiburg/informatik/ultimate/cdt/translation/implementation/base/CHandler.java
> +			mLogger.debug("left hand side expression in assignment: "+ leftOperand.getLrValue().toString());
remove this debug log message

2022-02-01 15:32 UTC, danieldietsch commented on trunk/source/CACSL2BoogieTranslator/src/de/uni_freiburg/informatik/ultimate/cdt/translation/implementation/base/CHandler.java
> +		 */
remove commented-out code

2022-02-01 15:32 UTC, danieldietsch commented on trunk/source/CACSL2BoogieTranslator/src/de/uni_freiburg/informatik/ultimate/cdt/translation/implementation/base/CHandler.java
> +		mStaticObjectsHandler.addGlobalVarDeclarationWithoutCDeclaration(auxvar.getVarDec());
fix indentation

2022-02-01 15:32 UTC, danieldietsch commented on trunk/source/CACSL2BoogieTranslator/src/de/uni_freiburg/informatik/ultimate/cdt/translation/implementation/base/expressiontranslation/BitabsTranslation.java
> + * This file is part of the ULTIMATE CACSL2BoogieTranslator plug-in.
add yourself to copyright header, extend times of others if you did not change substantial parts

2022-02-01 15:32 UTC, danieldietsch commented on trunk/source/CACSL2BoogieTranslator/src/de/uni_freiburg/informatik/ultimate/cdt/translation/implementation/base/expressiontranslation/BitabsTranslation.java
> +		Expression literal_1 = new IntegerLiteral(loc, BoogieType.TYPE_INT, "1");
use Ultimate coding convention

2022-02-01 15:43 UTC, cyruliu commented
> Lets wait for the results of the nightly build, then we should be able to merge.

Thanks, will work on the changes.

2022-02-01 15:55 UTC, danieldietsch commented
Actually, I had a closer look, it will take some more changes to make this mergeable. Ill look into it later.

2022-02-02 08:03 UTC, danieldietsch requested changes
Can you rename all the local variables in `BitabsTranslation` to fit Ultimate's coding convention? Local vars should be lower camel case without underscores, etc.

2022-02-02 14:22 UTC, cyruliu commented on trunk/source/CACSL2BoogieTranslator/src/de/uni_freiburg/informatik/ultimate/cdt/translation/implementation/base/expressiontranslation/BitabsTranslation.java
> +		Expression literal_1 = new IntegerLiteral(loc, BoogieType.TYPE_INT, "1");
Working on it.

2022-02-03 16:49 UTC, danieldietsch requested changes
Looks good, only one small thing left. 
Refactoring the whole thing s.t. it uses existing functions is a separate task :)

2022-02-03 16:49 UTC, danieldietsch commented on trunk/source/CACSL2BoogieTranslator/src/de/uni_freiburg/informatik/ultimate/cdt/translation/implementation/base/expressiontranslation/BitabsTranslation.java
> +			final IDispatcher main, final LocationFactory locationFactory, final IASTBinaryExpression node) {
the `m` prefix is only for global members.

2022-02-11 09:47 UTC, danieldietsch approved these changes

2022-02-11 10:09 UTC, merged